### ISSUE TITLE
distributed_train.sh

### ISSUE THREAD

**Issue by Joker-Y1** [sail-sg/inceptionnext#1]
Nice work!
I would like to fine tuning, but I can't find the 'distributed_train.sh' file"

**Comment by yuweihao** [comment]
Hi @Joker-Y1 ,

Many thanks for your reminder. I forgot to upload this file. I have fixed it. Thank you again.

**Comment by yuweihao** [comment]
Hi @Joker-Y1 ,

Sorry that I found I also forgot to copy utils.py when copying training code from repo [metaformer](https://github.com/sail-sg/metaformer). I fixed it and carefully tested the code. The training code in this repo completely works now.

**Comment by Joker-Y1** [comment]
@yuweihao Thanks for your reminder!!!
