### ISSUE TITLE
A Typo

### ISSUE THREAD

**Issue by PulsoX** [sail-sg/inceptionnext#2]
Dear author, Thankyou for your impressive work. I notice  a minor possible typo in your paper (arxiv version) in paragraph 3.2, "Complexity" part, line 3, where you wrote "incetion depthwise convolution" instead of "inception depthwise convolution". Maybe you can correct this mistake in your final version. Thankyou again for your contribution!

**Comment by yuweihao** [comment]
Thank you very much!
