### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xywlpo** [sail-sg/inceptionnext#4]
hi, thanks for your great work. When I use your code to train my datasets, there is a problem as followings:
there is no module named utils, and I cannot found a file named utils.py
![image](https://user-images.githubusercontent.com/728405/229772879-fa09af76-1ebb-48d8-b8a1-77b4b19ea9ce.png)

**Comment by yuweihao** [comment]
Oh, the train.py is copied from [metaformer](https://github.com/sail-sg/metaformer) and I forgot to copy its related utils.py. I have fixed it. Thank you for your reminder.
