### ISSUE TITLE
Error on pre-trained weights

### ISSUE THREAD

**Issue by suisui-su-crtl** [sail-sg/inceptionnext#8]
Hello, I tried to use inceptionnext as my backbone, the network is configured, but when loading of the pre-trained weights is wrong:
‘TypeError: a bytes-like object is required, not '_io.BufferedReader'
Can you give me a little help?

**Comment by suisui-su-crtl** [comment]
The same configuration trying to use convnext's pre-trained weights is fine, the problem may arise in the weights

**Comment by yuweihao** [comment]
Hi @suisui-su-crtl ,

I run the [InceptionNeXt colab example](https://colab.research.google.com/drive/1-CAPm6FNKYRbe_lAPxIBxsIH4xowgfg8?usp=sharing). The code runs successfully so the weights may be not the problem. Could you show more details of your case?

**Comment by suisui-su-crtl** [comment]
> Hi @suisui-su-crtl ,
> 
> I run the [InceptionNeXt colab example](https://colab.research.google.com/drive/1-CAPm6FNKYRbe_lAPxIBxsIH4xowgfg8?usp=sharing). The code runs successfully so the weights may be not the problem. Could you show more details of your case?

Thank you very much for your reply. I later tried to download the weights locally and the operation succeeded, which may be due to the network problem
